#!/usr/bin/env python3
from __future__ import annotations

import re
from html import escape
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

ROOT = Path(__file__).resolve().parent
STYLES = ROOT / "styles.css"
APP_JS = ROOT / "app.js"
DAILY_DIR = ROOT / "daily"

CSS_MARKER = "/* THE PRESS: wider article pages + nicer inline source links */"
CSS_BLOCK = r'''
/* THE PRESS: wider article pages + nicer inline source links */

/* Root article pages generated by build.py */
.page-article .article > .article-shell{
  width:100%;
  max-width:none;
  grid-template-columns:minmax(240px, 300px) minmax(0, 1fr);
}

/* Older daily article template in /daily/*.html */
.page-article .article-layout{
  width:min(calc(100% - 2rem), 1240px);
  margin-inline:auto;
  padding-block:1.4rem 3rem;
}

.page-article .article-layout > .article-shell{
  display:block;
  width:100%;
  max-width:1120px;
  margin-inline:auto;
}

/* Newer daily generator template */
.page-article .article-grid{
  display:grid;
  grid-template-columns:minmax(220px, 280px) minmax(0, 1fr);
  gap:1.6rem;
  align-items:start;
  margin-top:1.4rem;
}

.page-article .article-grid .article-aside,
.page-article .article-grid .article-body,
.page-article .article > .article-shell .article-aside,
.page-article .article > .article-shell .article-body{
  min-width:0;
}

.page-article .article-body{
  width:100%;
}

.page-article .article-body p,
.page-article .article-body li,
.page-article .article-body blockquote{
  max-width:84ch;
}

.page-article .article-layout > .article-shell > .article-body > *,
.page-article .article-grid > .article-body > *,
.page-article .article > .article-shell > .article-body > *{
  max-width:84ch;
}

.page-article .article-layout > .article-shell > .article-body > .related-block,
.page-article .article-layout > .article-shell > .article-body > figure,
.page-article .article-layout > .article-shell > .article-body > pre,
.page-article .article-grid > .article-body > .related-block,
.page-article .article-grid > .article-body > figure,
.page-article .article-grid > .article-body > pre,
.page-article .article > .article-shell > .article-body > .related-block,
.page-article .article > .article-shell > .article-body > figure,
.page-article .article > .article-shell > .article-body > pre{
  max-width:100%;
}

.page-article .article-sources,
.page-article .source-notes{
  margin-top:2rem;
}

.page-article .article-sources a,
.page-article .source-notes a{
  text-decoration:underline;
  overflow-wrap:anywhere;
}

.page-article .article-body .source-inline{
  display:inline-flex;
  align-items:center;
  vertical-align:baseline;
}

.page-article .article-body .source-inline a{
  display:inline-flex;
  align-items:center;
  gap:.35rem;
  margin-left:.2rem;
  padding:.12rem .55rem;
  border:1px solid var(--line);
  border-radius:999px;
  background:var(--accent-soft);
  color:var(--accent);
  font-size:.92em;
  font-weight:700;
  line-height:1.25;
  text-decoration:none;
  max-width:100%;
  overflow-wrap:anywhere;
}

.page-article .article-body .source-inline a:hover{
  text-decoration:none;
}

.topbar__link{
  color:var(--ink);
  font-weight:700;
}

@media (max-width: 1120px){
  .page-article .article-grid,
  .page-article .article > .article-shell{
    grid-template-columns:1fr;
  }
}

@media (max-width: 700px){
  .page-article .article-layout{
    width:min(calc(100% - 1rem), 1240px);
  }
}
'''.strip()

JS_CALL = "    repairInlineArticleSourceLinks(document);\n"
JS_SNIPPET = r'''

  function repairInlineArticleSourceLinks(root) {
    root.querySelectorAll('.article-body, [data-article-body]').forEach((body) => {
      if (!body || body.dataset.inlineSourceFixed === 'true') return;
      const before = body.innerHTML;
      const after = convertMarkdownSourceLinksToHtml(before);
      if (after !== before) {
        body.innerHTML = after;
      }
      body.dataset.inlineSourceFixed = 'true';
    });

    root.querySelectorAll('.article-body .source-inline a, .article-sources a, .source-notes a, .source-list a').forEach((a) => {
      const href = a.getAttribute('href') || '';
      if (!href) return;
      const cleaned = cleanTrackingUrl(href);
      if (cleaned) a.setAttribute('href', cleaned);
      if (/^https?:\/\//i.test(cleaned || href)) {
        a.setAttribute('target', '_blank');
        a.setAttribute('rel', 'noopener noreferrer');
      }
    });
  }

  function convertMarkdownSourceLinksToHtml(markup) {
    if (!markup || typeof markup !== 'string') return markup;

    let output = markup;

    output = output.replace(/\(\[([^\]]+?)\]\((https?:\/\/[^)\s<]+)\)\)/gi, (_, label, url) => {
      const cleaned = cleanTrackingUrl(url) || url;
      return `<span class="source-inline">(<a href="${escapeAttribute(cleaned)}" target="_blank" rel="noopener noreferrer">${escapeHtml(collapseWhitespace(label))}</a>)</span>`;
    });

    output = output.replace(/\[([^\]]+?)\]\((https?:\/\/[^)\s<]+)\)/gi, (_, label, url) => {
      const cleaned = cleanTrackingUrl(url) || url;
      return `<span class="source-inline"><a href="${escapeAttribute(cleaned)}" target="_blank" rel="noopener noreferrer">${escapeHtml(collapseWhitespace(label))}</a></span>`;
    });

    return output;
  }

  function cleanTrackingUrl(rawUrl) {
    try {
      const url = new URL(rawUrl, window.location.href);
      const drop = new Set(['fbclid', 'gclid', 'mc_cid', 'mc_eid', '_hsenc', '_hsmi']);

      Array.from(url.searchParams.keys()).forEach((key) => {
        const lower = key.toLowerCase();
        if (lower.startsWith('utm_') || drop.has(lower)) {
          url.searchParams.delete(key);
        }
      });

      if (url.pathname !== '/') {
        url.pathname = url.pathname.replace(/\/+$/, '');
      }

      return url.toString();
    } catch (_) {
      return rawUrl;
    }
  }
'''.rstrip() + "\n"

MARKDOWN_LINK_PARENS_RE = re.compile(r"\(\[([^\]]+?)\]\((https?://[^)\s<]+)\)\)", re.IGNORECASE)
MARKDOWN_LINK_RE = re.compile(r"\[([^\]]+?)\]\((https?://[^)\s<]+)\)", re.IGNORECASE)
ARTICLE_BODY_RE = re.compile(
    r'(<div class="article-body(?:"|[^>]*data-article-body[^>]*">)\s*)(.*?)(\s*</div>\s*<section class="article-sources">)',
    re.DOTALL,
)
SOURCE_SECTION_RE = re.compile(r'(<section class="article-sources">.*?</section>)', re.DOTALL)
ANCHOR_HREF_RE = re.compile(r'href="([^"]+)"')
ANCHOR_HREF_SINGLE_RE = re.compile(r"href='([^']+)'")
TRACKING_PREFIXES = ("utm_",)
TRACKING_KEYS = {"fbclid", "gclid", "mc_cid", "mc_eid", "_hsenc", "_hsmi"}


def clean_url(url: str) -> str:
    try:
        parts = urlsplit(url)
        cleaned_query = [
            (k, v)
            for k, v in parse_qsl(parts.query, keep_blank_values=True)
            if not k.lower().startswith(TRACKING_PREFIXES) and k.lower() not in TRACKING_KEYS
        ]
        path = parts.path.rstrip("/") if parts.path not in ("", "/") else parts.path
        return urlunsplit((parts.scheme, parts.netloc, path, urlencode(cleaned_query, doseq=True), parts.fragment))
    except Exception:
        return url


def make_inline_link(label: str, url: str, wrapped: bool) -> str:
    safe_label = escape(" ".join(label.split()))
    safe_url = escape(clean_url(url), quote=True)
    pill = f'<span class="source-inline"><a href="{safe_url}" target="_blank" rel="noopener noreferrer">{safe_label}</a></span>'
    return f'({pill})' if wrapped else pill


def fix_markdown_links(fragment: str) -> str:
    fragment = MARKDOWN_LINK_PARENS_RE.sub(lambda m: make_inline_link(m.group(1), m.group(2), True), fragment)
    fragment = MARKDOWN_LINK_RE.sub(lambda m: make_inline_link(m.group(1), m.group(2), False), fragment)
    return fragment


def fix_source_section(fragment: str) -> str:
    fragment = ANCHOR_HREF_RE.sub(lambda m: f'href="{escape(clean_url(m.group(1)), quote=True)}"', fragment)
    fragment = ANCHOR_HREF_SINGLE_RE.sub(lambda m: f"href='{escape(clean_url(m.group(1)), quote=True)}'", fragment)
    fragment = re.sub(r'<a\b(?![^>]*\btarget=)([^>]*)>', r'<a\1 target="_blank" rel="noopener noreferrer">', fragment)
    return fragment


def patch_styles() -> bool:
    if not STYLES.exists():
        raise SystemExit(f"Could not find {STYLES}")
    original = STYLES.read_text(encoding="utf-8")
    if CSS_MARKER in original:
        return False
    updated = original.rstrip() + "\n\n" + CSS_BLOCK + "\n"
    STYLES.write_text(updated, encoding="utf-8")
    return True


def patch_app_js() -> bool:
    if not APP_JS.exists():
        raise SystemExit(f"Could not find {APP_JS}")
    original = APP_JS.read_text(encoding="utf-8")
    updated = original

    if JS_CALL.strip() not in updated:
        needle = "    prettifySourceLinks(document);\n"
        if needle not in updated:
            raise SystemExit("Could not find prettifySourceLinks(document); in app.js")
        updated = updated.replace(needle, needle + JS_CALL, 1)

    if "function repairInlineArticleSourceLinks(root)" not in updated:
        insert_before = "  function sectionAliases(sectionName) {"
        if insert_before not in updated:
            insert_before = "})();"
            updated = updated.replace(insert_before, JS_SNIPPET + "\n" + insert_before, 1)
        else:
            updated = updated.replace(insert_before, JS_SNIPPET + "\n" + insert_before, 1)

    if updated != original:
        APP_JS.write_text(updated, encoding="utf-8")
        return True
    return False


def patch_daily_file(path: Path) -> bool:
    original = path.read_text(encoding="utf-8")
    updated = original

    body_match = ARTICLE_BODY_RE.search(updated)
    if body_match:
        fixed_body = fix_markdown_links(body_match.group(2))
        updated = updated[:body_match.start(2)] + fixed_body + updated[body_match.end(2):]

    updated = SOURCE_SECTION_RE.sub(lambda m: fix_source_section(m.group(1)), updated, count=1)

    if updated != original:
        path.write_text(updated, encoding="utf-8")
        return True
    return False


def patch_daily_html() -> tuple[int, int]:
    if not DAILY_DIR.exists():
        return (0, 0)
    checked = 0
    changed = 0
    for html_file in sorted(DAILY_DIR.glob("*.html")):
        checked += 1
        if patch_daily_file(html_file):
            changed += 1
    return checked, changed


def main() -> None:
    styles_changed = patch_styles()
    js_changed = patch_app_js()
    checked, changed = patch_daily_html()

    print("Done.")
    print(f"styles.css updated: {styles_changed}")
    print(f"app.js updated: {js_changed}")
    print(f"daily HTML checked: {checked}")
    print(f"daily HTML changed: {changed}")


if __name__ == "__main__":
    main()
