#!/usr/bin/env node

import fs from 'node:fs';
import vm from 'node:vm';

const momentsFile = 'assets/on-this-day-moments.js';

const CURATED = {
  '05-24': {
    year: 1844,
    title: 'First Telegraph Message',
    topic: 'Electrical telegraph',
    headline: 'Samuel Morse sent the first long-distance telegraph message from Washington to Baltimore: "What hath God wrought."',
    text: 'Samuel Morse sent the first long-distance telegraph message from Washington, D.C., to Baltimore, turning electricity into a practical communications system and shrinking political, financial, and social time.',
    source: 'https://en.wikipedia.org/wiki/What_hath_God_wrought',
    sourceLabel: 'Wikipedia: What hath God wrought',
    sourceDescription: 'First message sent by telegraph in the United States',
    visual: 'tech',
    palette: 'signal',
    scene: 'a telegraph room where electricity turns distance into instant information',
    stakes: 'a communications breakthrough that helped make the modern world faster, stranger, and more connected',
  },
  '05-25': {
    year: 1977,
    title: 'Star Wars Opens',
    topic: 'Star Wars',
    headline: 'Star Wars opened in theaters and rewired blockbuster cinema, fandom, special effects, merchandising, and popular mythology.',
    text: 'Star Wars opened in theaters, launching a global entertainment phenomenon that changed blockbuster filmmaking, visual effects, fan culture, merchandising, and the shared language of modern pop mythology.',
    source: 'https://en.wikipedia.org/wiki/Star_Wars_(film)',
    sourceLabel: 'Wikipedia: Star Wars',
    sourceDescription: '1977 space opera film and global cultural phenomenon',
    visual: 'culture',
    palette: 'stage',
    scene: 'a 1977 movie theater line where science fiction becomes mass culture',
    stakes: 'a pop-culture ignition point whose aftershocks ran through cinema, toys, music, design, and fandom',
  },
  '05-26': {
    year: 1940,
    title: 'Dunkirk Evacuation Begins',
    topic: 'Dunkirk evacuation',
    headline: 'Operation Dynamo began as Allied soldiers were evacuated from Dunkirk under attack during World War II.',
    text: 'The Dunkirk evacuation began, sending naval vessels and civilian boats across the Channel to rescue Allied soldiers trapped on the beaches of northern France during World War II.',
    source: 'https://en.wikipedia.org/wiki/Dunkirk_evacuation',
    sourceLabel: 'Wikipedia: Dunkirk evacuation',
    sourceDescription: '1940 evacuation of Allied soldiers during World War II',
    visual: 'conflict',
    palette: 'battlefield',
    scene: 'a beach evacuation where soldiers, smoke, small boats, and sea weather carry the stakes of a war',
    stakes: 'a survival operation that became one of the defining images of World War II',
  },
  '05-27': {
    year: 1937,
    title: 'Golden Gate Bridge Opens',
    topic: 'Golden Gate Bridge',
    headline: 'The Golden Gate Bridge opened to pedestrians, revealing one of the modern world’s most recognizable engineering landmarks.',
    text: 'The Golden Gate Bridge opened to pedestrians, joining San Francisco and Marin County with a suspension bridge that became an icon of engineering, migration, risk, and American modernity.',
    source: 'https://en.wikipedia.org/wiki/Golden_Gate_Bridge',
    sourceLabel: 'Wikipedia: Golden Gate Bridge',
    sourceDescription: 'Suspension bridge spanning the Golden Gate strait',
    visual: 'transport',
    palette: 'voyage',
    scene: 'a foggy bridge deck where engineering turns a dangerous strait into a public crossing',
    stakes: 'an engineering feat that changed movement, skyline, labor memory, and the visual identity of a city',
  },
  '05-28': {
    year: 1998,
    title: 'Pakistan Nuclear Tests',
    topic: 'Chagai-I',
    headline: 'Pakistan conducted the Chagai-I nuclear tests, becoming the seventh country to publicly test nuclear weapons.',
    text: 'Pakistan conducted the Chagai-I nuclear tests in Balochistan, declaring itself a nuclear-armed state and changing the strategic balance of South Asia and global nonproliferation politics.',
    source: 'https://en.wikipedia.org/wiki/Chagai-I',
    sourceLabel: 'Wikipedia: Chagai-I',
    sourceDescription: '1998 underground nuclear tests conducted by Pakistan',
    visual: 'science',
    palette: 'signal',
    scene: 'a remote mountain test range where geology, secrecy, nationalism, and nuclear power collide',
    stakes: 'a nuclear turning point with regional, global, scientific, and political consequences',
  },
  '05-29': {
    year: 1953,
    title: 'Everest Summit',
    topic: '1953 British Mount Everest expedition',
    headline: 'Tenzing Norgay and Edmund Hillary reached the summit of Mount Everest.',
    text: 'Tenzing Norgay and Edmund Hillary reached the summit of Mount Everest, turning the highest point on Earth into a global symbol of endurance, empire, Sherpa expertise, and human ambition.',
    source: 'https://en.wikipedia.org/wiki/1953_British_Mount_Everest_expedition',
    sourceLabel: 'Wikipedia: 1953 British Mount Everest expedition',
    sourceDescription: 'First confirmed ascent of Mount Everest',
    visual: 'transport',
    palette: 'voyage',
    scene: 'a high-altitude Himalayan summit where ice, wind, oxygen gear, and human endurance meet',
    stakes: 'a mountain moment that became world myth and also depended on local knowledge, labor, and skill',
  },
  '05-30': {
    year: 1431,
    title: 'Joan of Arc Executed',
    topic: 'Joan of Arc',
    headline: 'Joan of Arc was executed in Rouen, becoming one of history’s most enduring symbols of faith, war, politics, and martyrdom.',
    text: 'Joan of Arc was executed in Rouen after a politically charged trial, transforming a young military and religious figure into a lasting symbol of martyrdom, nationalism, gender, and power.',
    source: 'https://en.wikipedia.org/wiki/Joan_of_Arc',
    sourceLabel: 'Wikipedia: Joan of Arc',
    sourceDescription: 'French military leader and Catholic saint',
    visual: 'civic',
    palette: 'public-square',
    scene: 'a medieval city square where power, spectacle, faith, and fear turn a trial into legend',
    stakes: 'a terrifying public death that became one of the most famous stories in European history',
  },
  '05-31': {
    year: 1921,
    title: 'Tulsa Race Massacre Begins',
    topic: 'Tulsa race massacre',
    headline: 'The Tulsa race massacre began as white mobs attacked the prosperous Black neighborhood of Greenwood.',
    text: 'The Tulsa race massacre began in Oklahoma, destroying much of the Greenwood District, killing Black residents, displacing thousands, and becoming one of the starkest examples of racial terror and economic destruction in American history.',
    source: 'https://en.wikipedia.org/wiki/Tulsa_race_massacre',
    sourceLabel: 'Wikipedia: Tulsa race massacre',
    sourceDescription: '1921 racial massacre in Tulsa, Oklahoma',
    visual: 'rights',
    palette: 'public-square',
    scene: 'Greenwood before and during catastrophe, with Black residents, smoke, storefronts, and survival at the center',
    stakes: 'a racial-terror event whose destruction of Black life and wealth still echoes through history',
  },
  '06-01': {
    year: 1980,
    title: 'CNN Launches',
    topic: 'CNN',
    headline: 'CNN began broadcasting, launching the first 24-hour television news network.',
    text: 'CNN began broadcasting as the first 24-hour television news network, changing how breaking news, crises, markets, wars, disasters, and politics entered everyday life in real time.',
    source: 'https://en.wikipedia.org/wiki/CNN',
    sourceLabel: 'Wikipedia: CNN',
    sourceDescription: 'American 24-hour cable news network',
    visual: 'tech',
    palette: 'signal',
    scene: 'an early cable-news control room where satellite dishes, monitors, anchors, and live time reshape public attention',
    stakes: 'a media-infrastructure shift that made news feel continuous, immediate, and global',
  },
  '06-02': {
    year: 1966,
    title: 'Surveyor 1 Lands on the Moon',
    topic: 'Surveyor 1',
    headline: 'Surveyor 1 became the first American spacecraft to soft-land on the Moon.',
    text: 'Surveyor 1 soft-landed on the Moon, proving that a spacecraft could land safely on the lunar surface and helping prepare the way for Apollo.',
    source: 'https://en.wikipedia.org/wiki/Surveyor_1',
    sourceLabel: 'Wikipedia: Surveyor 1',
    sourceDescription: 'First American lunar soft-landing mission',
    visual: 'space',
    palette: 'lunar',
    scene: 'a robotic spacecraft sitting alone on the Moon before humans arrive',
    stakes: 'a robotic proof point that turned lunar landing from speculation into engineering sequence',
  },
  '06-03': {
    year: 1965,
    title: 'First American Spacewalk',
    topic: 'Gemini 4',
    headline: 'Ed White performed the first American spacewalk during Gemini 4.',
    text: 'Ed White performed the first American spacewalk during Gemini 4, floating outside the spacecraft as the space race entered a new and startlingly human visual phase.',
    source: 'https://en.wikipedia.org/wiki/Gemini_4',
    sourceLabel: 'Wikipedia: Gemini 4',
    sourceDescription: 'NASA mission that included the first American spacewalk',
    visual: 'space',
    palette: 'lunar',
    scene: 'a human body suspended outside a small spacecraft above the curve of Earth',
    stakes: 'a space-race image that made human vulnerability and technical daring visible at once',
  },
  '06-04': {
    year: 1989,
    title: 'Tiananmen Crackdown',
    topic: '1989 Tiananmen Square protests and massacre',
    headline: 'Chinese troops moved against pro-democracy demonstrators in Beijing, ending the Tiananmen Square protests in bloodshed.',
    text: 'Chinese troops moved against pro-democracy demonstrators in Beijing, ending the Tiananmen Square protests and making Tiananmen one of the most consequential and contested political memories of the late twentieth century.',
    source: 'https://en.wikipedia.org/wiki/1989_Tiananmen_Square_protests_and_massacre',
    sourceLabel: 'Wikipedia: 1989 Tiananmen Square protests and massacre',
    sourceDescription: '1989 pro-democracy protests and military crackdown in Beijing',
    visual: 'protest',
    palette: 'public-square',
    scene: 'a Beijing avenue after a night of crackdown, with bicycles, smoke, armored silhouettes, and public fear',
    stakes: 'a political rupture whose images, silences, and memory still shape global conversations about power',
  },
  '06-05': {
    year: 1981,
    title: 'First AIDS Report',
    topic: 'HIV/AIDS',
    headline: 'The CDC published the first official report of what became known as AIDS.',
    text: 'The CDC published a report describing unusual pneumonia cases in five young gay men in Los Angeles, an early public signal of what became the global HIV/AIDS crisis.',
    source: 'https://en.wikipedia.org/wiki/HIV/AIDS',
    sourceLabel: 'Wikipedia: HIV/AIDS',
    sourceDescription: 'Global pandemic caused by HIV infection',
    visual: 'medicine',
    palette: 'signal',
    scene: 'an early-1980s public-health desk where a small medical report foreshadows a global epidemic',
    stakes: 'a medical notice that became the opening trace of one of the defining public-health crises of modern history',
  },
  '06-06': {
    year: 1944,
    title: 'D-Day',
    topic: 'Normandy landings',
    headline: 'Allied forces landed in Normandy on D-Day, opening the Western Front in Nazi-occupied Europe.',
    text: 'Allied forces landed on the beaches of Normandy on D-Day, beginning the liberation of Western Europe from Nazi occupation and creating one of the most consequential military operations in history.',
    source: 'https://en.wikipedia.org/wiki/Normandy_landings',
    sourceLabel: 'Wikipedia: Normandy landings',
    sourceDescription: 'Allied invasion of Normandy during World War II',
    visual: 'conflict',
    palette: 'battlefield',
    scene: 'landing craft, surf, smoke, obstacles, soldiers, and scale on a stormy Normandy beach',
    stakes: 'a military turning point whose cost and consequence reshaped the twentieth century',
  },
  '06-07': {
    year: 1893,
    title: 'Gandhi Removed from Train',
    topic: 'Mahatma Gandhi',
    headline: 'Mahatma Gandhi was removed from a train at Pietermaritzburg, a formative moment in his resistance to racial discrimination.',
    text: 'Mahatma Gandhi was removed from a first-class railway compartment at Pietermaritzburg station in South Africa, an experience he later described as formative in his fight against racial discrimination and colonial injustice.',
    source: 'https://en.wikipedia.org/wiki/Mahatma_Gandhi',
    sourceLabel: 'Wikipedia: Mahatma Gandhi',
    sourceDescription: 'Leader of Indian independence movement and nonviolent resistance',
    visual: 'rights',
    palette: 'public-square',
    scene: 'a cold colonial railway platform where exclusion becomes the seed of a resistance philosophy',
    stakes: 'a personal humiliation that helped shape a global language of civil resistance',
  },
  '06-08': {
    year: 1783,
    title: 'Laki Eruption Begins',
    topic: 'Laki',
    headline: 'The Laki volcanic eruption began in Iceland, triggering deadly haze, famine, and climate effects across the Northern Hemisphere.',
    text: 'The Laki volcanic eruption began in Iceland, releasing poisonous gases and haze that devastated Iceland, affected climate and harvests across Europe, and became one of history’s most consequential environmental disasters.',
    source: 'https://en.wikipedia.org/wiki/Laki',
    sourceLabel: 'Wikipedia: Laki',
    sourceDescription: '1783 volcanic eruption in Iceland',
    visual: 'science',
    palette: 'battlefield',
    scene: 'a fissure eruption under an ash-dark sky, with lava, farms, livestock, and poisoned haze showing environmental scale',
    stakes: 'a volcanic disaster that turned geology into famine, weather, death, and global atmospheric memory',
  },
  '06-09': {
    year: 68,
    title: 'Nero Dies',
    topic: 'Nero',
    headline: 'Nero died, ending the Julio-Claudian dynasty and plunging Rome into the Year of the Four Emperors.',
    text: 'Nero died outside Rome, ending the Julio-Claudian dynasty and triggering the Year of the Four Emperors, a succession crisis that exposed the volatility of imperial power.',
    source: 'https://en.wikipedia.org/wiki/Nero',
    sourceLabel: 'Wikipedia: Nero',
    sourceDescription: 'Roman emperor whose death ended the Julio-Claudian dynasty',
    visual: 'civic',
    palette: 'public-square',
    scene: 'a Roman road and villa at dawn where imperial power collapses into rumor, flight, and succession crisis',
    stakes: 'an ancient political break that showed how fragile empire could become once legitimacy failed',
  },
  '06-10': {
    year: 1967,
    title: 'Six-Day War Ends',
    topic: 'Six-Day War',
    headline: 'The Six-Day War ended, redrawing the political and military map of the Middle East.',
    text: 'The Six-Day War ended after Israel captured territories including the Sinai Peninsula, Gaza Strip, West Bank, East Jerusalem, and Golan Heights, reshaping Middle Eastern politics for generations.',
    source: 'https://en.wikipedia.org/wiki/Six-Day_War',
    sourceLabel: 'Wikipedia: Six-Day War',
    sourceDescription: '1967 Arab-Israeli war',
    visual: 'conflict',
    palette: 'battlefield',
    scene: 'a desert road and old-city edge where maps, soldiers, civilians, and dust reveal a region transformed',
    stakes: 'a brief war whose territorial and political consequences remain globally consequential',
  },
  '06-11': {
    year: 1963,
    title: 'University of Alabama Desegregation',
    topic: 'Stand in the Schoolhouse Door',
    headline: 'Vivian Malone and James Hood registered at the University of Alabama after federal intervention.',
    text: 'Vivian Malone and James Hood registered at the University of Alabama after federal intervention, defeating Governor George Wallace’s symbolic attempt to block desegregation at the schoolhouse door.',
    source: 'https://en.wikipedia.org/wiki/Stand_in_the_Schoolhouse_Door',
    sourceLabel: 'Wikipedia: Stand in the Schoolhouse Door',
    sourceDescription: '1963 confrontation over University of Alabama desegregation',
    visual: 'rights',
    palette: 'public-square',
    scene: 'Black students crossing a campus threshold under federal protection while cameras, state power, and history watch',
    stakes: 'a civil-rights confrontation where education, federal authority, segregation, and courage met in public view',
  },
  '06-12': {
    year: 1967,
    title: 'Loving v. Virginia',
    topic: 'Loving v. Virginia',
    headline: 'The U.S. Supreme Court struck down laws banning interracial marriage.',
    text: 'The U.S. Supreme Court decided Loving v. Virginia, striking down bans on interracial marriage and affirming marriage as a civil right protected by the Constitution.',
    source: 'https://en.wikipedia.org/wiki/Loving_v._Virginia',
    sourceLabel: 'Wikipedia: Loving v. Virginia',
    sourceDescription: 'Landmark U.S. Supreme Court civil-rights case',
    visual: 'rights',
    palette: 'public-square',
    scene: 'an interracial couple and civil-rights lawyers outside a courthouse as private love becomes constitutional history',
    stakes: 'a legal victory that changed family, citizenship, race, privacy, and equality in everyday life',
  },
  '06-13': {
    year: 1966,
    title: 'Miranda v. Arizona',
    topic: 'Miranda v. Arizona',
    headline: 'The U.S. Supreme Court decided Miranda v. Arizona, requiring police to inform suspects of key rights.',
    text: 'The Supreme Court decided Miranda v. Arizona, requiring police to inform detained suspects of their rights to silence and counsel before custodial interrogation.',
    source: 'https://en.wikipedia.org/wiki/Miranda_v._Arizona',
    sourceLabel: 'Wikipedia: Miranda v. Arizona',
    sourceDescription: 'Landmark criminal procedure decision',
    visual: 'rights',
    palette: 'signal',
    scene: 'a 1960s police station where a rights card, recorder, suspect, and lawyer redefine interrogation',
    stakes: 'a courtroom decision that entered everyday language and changed criminal procedure around the world',
  },
  '06-14': {
    year: 1940,
    title: 'German Troops Enter Paris',
    topic: 'Paris in World War II',
    headline: 'German troops entered Paris during World War II.',
    text: 'German troops entered Paris during World War II, turning one of the world’s great capitals into an occupied city and marking a devastating moment in the fall of France.',
    source: 'https://en.wikipedia.org/wiki/Paris_in_World_War_II',
    sourceLabel: 'Wikipedia: Paris in World War II',
    sourceDescription: 'History of Paris during German occupation',
    visual: 'conflict',
    palette: 'battlefield',
    scene: 'an occupied Paris boulevard with shuttered shops, civilians, soldiers, bicycles, and a city holding its breath',
    stakes: 'a capital’s fall that made the war’s danger visible in architecture, silence, and occupation',
  },
  '06-15': {
    year: 1215,
    title: 'Magna Carta',
    topic: 'Magna Carta',
    headline: 'King John sealed Magna Carta at Runnymede.',
    text: 'King John sealed Magna Carta at Runnymede, creating a charter that became a long-lived symbol of limits on power, due process, and the rule of law.',
    source: 'https://en.wikipedia.org/wiki/Magna_Carta',
    sourceLabel: 'Wikipedia: Magna Carta',
    sourceDescription: '1215 English charter of rights and limits on royal power',
    visual: 'civic',
    palette: 'public-square',
    scene: 'a muddy meadow by the Thames where parchment, seals, armed barons, clergy, and royal pressure reshape law',
    stakes: 'a medieval political settlement whose afterlife became global legal mythology',
  },
  '06-16': {
    year: 1963,
    title: 'First Woman in Space',
    topic: 'Valentina Tereshkova',
    headline: 'Valentina Tereshkova became the first woman in space aboard Vostok 6.',
    text: 'Valentina Tereshkova launched aboard Vostok 6 and became the first woman in space, orbiting Earth and transforming the gender symbolism of the space age.',
    source: 'https://en.wikipedia.org/wiki/Valentina_Tereshkova',
    sourceLabel: 'Wikipedia: Valentina Tereshkova',
    sourceDescription: 'First woman in space',
    visual: 'space',
    palette: 'lunar',
    scene: 'a Soviet launch-and-control moment centered on a woman cosmonaut entering space history',
    stakes: 'a spaceflight milestone where gender, propaganda, engineering, and human daring all met in orbit',
  },
  '06-17': {
    year: 1972,
    title: 'Watergate Break-In',
    topic: 'Watergate scandal',
    headline: 'Five men were arrested breaking into Democratic National Committee headquarters at the Watergate complex.',
    text: 'Five men were arrested breaking into Democratic National Committee headquarters at the Watergate complex, beginning the scandal that led to investigations, constitutional crisis, and President Nixon’s resignation.',
    source: 'https://en.wikipedia.org/wiki/Watergate_scandal',
    sourceLabel: 'Wikipedia: Watergate scandal',
    sourceDescription: 'U.S. political scandal that led to Nixon’s resignation',
    visual: 'crime',
    palette: 'signal',
    scene: 'a 1970s office-and-hotel complex at night where tape, tools, flashlights, guards, and paperwork become constitutional crisis',
    stakes: 'a burglary that exposed abuses of power and changed journalism, law, and presidential accountability',
  },
  '06-18': {
    year: 1815,
    title: 'Battle of Waterloo',
    topic: 'Battle of Waterloo',
    headline: 'Napoleon was defeated at the Battle of Waterloo.',
    text: 'Napoleon was defeated at the Battle of Waterloo, ending the Napoleonic Wars and reshaping European power, diplomacy, and military memory for the nineteenth century.',
    source: 'https://en.wikipedia.org/wiki/Battle_of_Waterloo',
    sourceLabel: 'Wikipedia: Battle of Waterloo',
    sourceDescription: '1815 battle ending Napoleon’s rule',
    visual: 'conflict',
    palette: 'battlefield',
    scene: 'a rain-soaked battlefield of mud, smoke, cavalry, infantry squares, and exhausted survivors after empire breaks',
    stakes: 'a battlefield defeat that became shorthand for the collapse of overwhelming ambition',
  },
  '06-19': {
    year: 1865,
    title: 'Juneteenth',
    topic: 'Juneteenth',
    headline: 'Enslaved people in Galveston, Texas, were informed of emancipation.',
    text: 'Union troops arrived in Galveston, Texas, and announced that enslaved people were free, making Juneteenth one of the central commemorations of emancipation and Black freedom in the United States.',
    source: 'https://en.wikipedia.org/wiki/Juneteenth',
    sourceLabel: 'Wikipedia: Juneteenth',
    sourceDescription: 'Holiday commemorating emancipation in the United States',
    visual: 'rights',
    palette: 'public-square',
    scene: 'Black families in Galveston hearing freedom announced amid Union troops, church bells, heat, dust, and stunned joy',
    stakes: 'an emancipation moment where law finally reached people who had been kept from freedom',
  },
  '06-20': {
    year: 1975,
    title: 'Jaws Released',
    topic: 'Jaws (film)',
    headline: 'Jaws opened in theaters and helped create the modern summer blockbuster.',
    text: 'Jaws opened in theaters, terrifying audiences and helping invent the modern summer blockbuster through mass release, television advertising, suspense editing, and event-film culture.',
    source: 'https://en.wikipedia.org/wiki/Jaws_(film)',
    sourceLabel: 'Wikipedia: Jaws',
    sourceDescription: '1975 thriller film and blockbuster turning point',
    visual: 'culture',
    palette: 'stage',
    scene: 'a 1975 beach-town movie theater and seaside street where fear, marketing, and summer culture collide',
    stakes: 'a film release that changed Hollywood economics and the rhythm of popular culture',
  },
  '06-21': {
    year: 1948,
    title: 'Manchester Baby Runs First Program',
    topic: 'Manchester Baby',
    headline: 'The Manchester Baby ran the first program stored in electronic memory.',
    text: 'The Manchester Baby ran the first stored program, proving a fundamental principle of modern computing and helping open the path to the software age.',
    source: 'https://en.wikipedia.org/wiki/Manchester_Baby',
    sourceLabel: 'Wikipedia: Manchester Baby',
    sourceDescription: 'First electronic stored-program computer',
    visual: 'tech',
    palette: 'signal',
    scene: 'a postwar computer lab where glowing cathode tubes, cables, notebooks, and machine heat create software’s origin point',
    stakes: 'a quiet machine-room breakthrough behind almost every later digital revolution',
  },
  '06-22': {
    year: 1941,
    title: 'Operation Barbarossa',
    topic: 'Operation Barbarossa',
    headline: 'Nazi Germany launched Operation Barbarossa, invading the Soviet Union.',
    text: 'Nazi Germany launched Operation Barbarossa, the largest invasion in history, opening a brutal Eastern Front that became central to World War II’s outcome and human cost.',
    source: 'https://en.wikipedia.org/wiki/Operation_Barbarossa',
    sourceLabel: 'Wikipedia: Operation Barbarossa',
    sourceDescription: '1941 Axis invasion of the Soviet Union',
    visual: 'conflict',
    palette: 'battlefield',
    scene: 'a dawn border landscape of tanks, maps, dust, civilians, and soldiers as the Eastern Front opens',
    stakes: 'an invasion whose scale, ideology, and violence reshaped the war and the twentieth century',
  },
  '06-23': {
    year: 2016,
    title: 'Brexit Referendum',
    topic: '2016 United Kingdom European Union membership referendum',
    headline: 'The United Kingdom voted to leave the European Union.',
    text: 'The United Kingdom voted to leave the European Union in the Brexit referendum, triggering years of political turmoil, economic uncertainty, constitutional argument, and European realignment.',
    source: 'https://en.wikipedia.org/wiki/2016_United_Kingdom_European_Union_membership_referendum',
    sourceLabel: 'Wikipedia: Brexit referendum',
    sourceDescription: '2016 UK referendum on EU membership',
    visual: 'civic',
    palette: 'signal',
    scene: 'a diverse results-night city street and counting hall where screens, ballots, rain, flags, and stunned faces capture a political rupture',
    stakes: 'a democratic shock that changed the United Kingdom’s relationship with Europe and with itself',
  },
  '06-24': {
    year: 1948,
    title: 'Berlin Blockade Begins',
    topic: 'Berlin Blockade',
    headline: 'The Soviet Union began the Berlin Blockade, prompting the Berlin Airlift.',
    text: 'The Soviet Union began the Berlin Blockade, cutting off Western land access to Berlin and prompting the Berlin Airlift, one of the Cold War’s defining confrontations.',
    source: 'https://en.wikipedia.org/wiki/Berlin_Blockade',
    sourceLabel: 'Wikipedia: Berlin Blockade',
    sourceDescription: '1948–1949 Cold War crisis over Berlin',
    visual: 'transport',
    palette: 'signal',
    scene: 'a divided Berlin airfield where cargo aircraft, children, coal sacks, runway lights, and blockade anxiety turn logistics into geopolitics',
    stakes: 'a Cold War crisis in which supply planes, city survival, and superpower pressure filled the sky',
  },
  '06-25': {
    year: 2009,
    title: 'Michael Jackson Dies',
    topic: 'Michael Jackson',
    headline: 'Michael Jackson died, triggering a worldwide pop-culture shock and public mourning.',
    text: 'Michael Jackson died in Los Angeles, sending shock through global music culture and turning streets, arenas, television, and the early social web into shared spaces of mourning.',
    source: 'https://en.wikipedia.org/wiki/Death_of_Michael_Jackson',
    sourceLabel: 'Wikipedia: Death of Michael Jackson',
    sourceDescription: '2009 death of the global pop music figure',
    visual: 'music',
    palette: 'stage',
    scene: 'a neon-lit global street vigil where fans, flowers, television trucks, cassette-era memories, and phone screens collide',
    stakes: 'a pop-culture rupture that showed the scale of modern celebrity, music memory, broadcast mourning, and internet-era attention',
  },
  '06-26': {
    year: 1997,
    title: "Harry Potter's First Book Published",
    topic: "Harry Potter and the Philosopher's Stone",
    headline: "Harry Potter and the Philosopher's Stone was first published in the United Kingdom.",
    text: "Harry Potter and the Philosopher's Stone was first published in the United Kingdom, beginning a book series that became a worldwide publishing, film, fandom, and youth-culture phenomenon.",
    source: 'https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone',
    sourceLabel: "Wikipedia: Harry Potter and the Philosopher's Stone",
    sourceDescription: '1997 fantasy novel and global publishing phenomenon',
    visual: 'culture',
    palette: 'stage',
    scene: 'a colorful 1997 bookshop window and children discovering a small fantasy hardback before the world knows what it will become',
    stakes: 'a publishing spark that remade children’s literature, fandom, film franchising, midnight release culture, and global reading habits',
  },
  '06-27': {
    year: 1972,
    title: 'Atari Founded',
    topic: 'Atari, Inc.',
    headline: 'Atari was founded in California, helping launch the modern video-game industry.',
    text: 'Atari was incorporated in California, helping turn electronic games from engineering curiosities into arcades, home consoles, youth culture, and a global interactive-entertainment industry.',
    source: 'https://en.wikipedia.org/wiki/Atari,_Inc.',
    sourceLabel: 'Wikipedia: Atari, Inc.',
    sourceDescription: 'American video game and home-computer company founded in 1972',
    visual: 'tech',
    palette: 'neon',
    scene: 'a scrappy 1970s Silicon Valley workshop where oscilloscopes, wood-paneled prototypes, coin-op cabinets, solder smoke, and neon arcade color begin gaming culture',
    stakes: 'a founding moment for commercial video games, arcades, home consoles, and the idea that software could become pop culture',
  },
  '06-28': {
    year: 1969,
    title: 'Stonewall Uprising',
    topic: 'Stonewall riots',
    headline: 'The Stonewall uprising began after a police raid at the Stonewall Inn in New York City.',
    text: 'The Stonewall uprising began in Greenwich Village after a police raid at the Stonewall Inn, becoming a catalytic moment in modern LGBTQ rights, protest culture, and queer public memory.',
    source: 'https://en.wikipedia.org/wiki/Stonewall_riots',
    sourceLabel: 'Wikipedia: Stonewall riots',
    sourceDescription: '1969 LGBTQ uprising in New York City',
    visual: 'rights',
    palette: 'neon',
    scene: 'a hot Greenwich Village night of neon bar light, street resistance, queer community, police pressure, broken glass, and defiant movement',
    stakes: 'a rights uprising whose energy reshaped identity, politics, pride, and public space around the world',
  },
  '06-29': {
    year: 2007,
    title: 'First iPhone Goes on Sale',
    topic: 'iPhone (1st generation)',
    headline: 'The first iPhone went on sale, changing phones, software, photography, music, maps, and the mobile internet.',
    text: 'The first iPhone went on sale in the United States, turning a product launch into a mobile-computing shift that changed phones, apps, cameras, maps, music, payments, and daily attention.',
    source: 'https://en.wikipedia.org/wiki/IPhone_(1st_generation)',
    sourceLabel: 'Wikipedia: iPhone (1st generation)',
    sourceDescription: 'First-generation smartphone released in 2007',
    visual: 'tech',
    palette: 'signal',
    scene: 'a bright 2007 glass-front store line where early smartphones, street reflections, news cameras, and excited buyers signal the pocket-computing era',
    stakes: 'a consumer-tech launch that helped move the internet from desks into hands and pockets',
  },
  '06-30': {
    year: 1960,
    title: 'Congo Becomes Independent',
    topic: 'Independence of the Democratic Republic of the Congo',
    headline: 'The Republic of the Congo became independent from Belgium.',
    text: 'The Republic of the Congo became independent from Belgium, placing decolonization, mineral wealth, Cold War pressure, and African self-determination on a volatile world stage.',
    source: 'https://en.wikipedia.org/wiki/Independence_of_the_Democratic_Republic_of_the_Congo',
    sourceLabel: 'Wikipedia: Independence of the Democratic Republic of the Congo',
    sourceDescription: '1960 independence of Congo from Belgium',
    visual: 'civic',
    palette: 'public-square',
    scene: 'a vivid Leopoldville independence day street with Congolese crowds, cloth patterns, radios, bicycles, flags, speeches, drums, and humid tropical color',
    stakes: 'a decolonization landmark whose hopes and crises became central to African, Cold War, and resource politics',
  },
  '07-01': {
    year: 1979,
    title: 'Sony Walkman Goes on Sale',
    topic: 'Walkman',
    headline: 'The first Sony Walkman went on sale in Japan, changing how people carried music through daily life.',
    text: 'The first Sony Walkman went on sale in Japan, helping make music portable, private, stylish, and personal long before smartphones and streaming.',
    source: 'https://en.wikipedia.org/wiki/Walkman',
    sourceLabel: 'Wikipedia: Walkman',
    sourceDescription: 'Portable cassette player launched in Japan in 1979',
    visual: 'tech',
    palette: 'neon',
    scene: 'a saturated 1979 Tokyo street where a blue-and-silver cassette player, orange headphones, record shops, train lights, and youth fashion make portable music visible',
    stakes: 'a consumer-electronics turn that changed listening, commuting, street style, product design, and personal media',
  },
  '07-02': {
    year: 1964,
    title: 'Civil Rights Act Signed',
    topic: 'Civil Rights Act of 1964',
    headline: 'The Civil Rights Act of 1964 was signed into law, outlawing major forms of segregation and discrimination.',
    text: 'The Civil Rights Act of 1964 was signed into law, outlawing major forms of segregation and discrimination in public accommodations, employment, and education.',
    source: 'https://en.wikipedia.org/wiki/Civil_Rights_Act_of_1964',
    sourceLabel: 'Wikipedia: Civil Rights Act of 1964',
    sourceDescription: 'Landmark U.S. civil-rights legislation',
    visual: 'rights',
    palette: 'public-square',
    scene: 'a vivid civil-rights newsroom and street celebration where Black organizers, newspapers, television cameras, courthouse steps, and summer light carry the law into public life',
    stakes: 'a legal and political landmark that transformed American citizenship, public space, labor, education, and civil-rights enforcement',
  },
  '07-03': {
    year: 1985,
    title: 'Back to the Future Opens',
    topic: 'Back to the Future',
    headline: 'Back to the Future opened in theaters and became one of the defining science-fiction comedies of the 1980s.',
    text: 'Back to the Future opened in theaters, turning time travel, teen comedy, rock-and-roll nostalgia, and pop-science style into a durable global movie language.',
    source: 'https://en.wikipedia.org/wiki/Back_to_the_Future',
    sourceLabel: 'Wikipedia: Back to the Future',
    sourceDescription: '1985 science-fiction comedy film',
    visual: 'culture',
    palette: 'neon',
    scene: 'a saturated 1985 movie-theater night with chrome cars, arcade lights, cassette jackets, lightning-sky reflections, and a crowd stepping into time-travel pop culture',
    stakes: 'a film release that fused retro style, science-fiction play, music, cars, and teen pop into a generational reference point',
  },
  '07-04': {
    year: 2012,
    title: 'Higgs Boson Discovery Announced',
    topic: 'Higgs boson',
    headline: 'CERN announced the discovery of a new particle consistent with the Higgs boson.',
    text: 'CERN announced that ATLAS and CMS had discovered a new particle consistent with the Higgs boson, confirming a central piece of the Standard Model after decades of searching.',
    source: 'https://home.cern/news/press-release/physics/higgs-boson-ten-years-after-its-discovery',
    sourceLabel: 'CERN: The Higgs boson, ten years after its discovery',
    sourceDescription: 'CERN account of the July 4, 2012 Higgs boson announcement',
    visual: 'science',
    palette: 'signal',
    scene: 'a glowing CERN auditorium and detector-control room where physicists, particle-event displays, blue screens, cables, and applause make invisible physics public',
    stakes: 'a scientific discovery that completed a missing piece of particle physics and became a rare global celebration of fundamental science',
  },
  '07-05': {
    year: 1996,
    title: 'Dolly the Sheep Is Born',
    topic: 'Dolly (sheep)',
    headline: 'Dolly the sheep, the first mammal cloned from an adult somatic cell, was born.',
    text: 'Dolly the sheep was born at the Roslin Institute, becoming the first mammal cloned from an adult somatic cell and transforming public debate about genetics, biotechnology, and identity.',
    source: 'https://en.wikipedia.org/wiki/Dolly_(sheep)',
    sourceLabel: 'Wikipedia: Dolly (sheep)',
    sourceDescription: 'First mammal cloned from an adult somatic cell',
    visual: 'medicine',
    palette: 'signal',
    scene: 'a bright 1990s biotech lab and lambing room where a newborn sheep, lab notebooks, incubators, DNA gels, and stunned scientists make cloning tangible',
    stakes: 'a biotechnology milestone that changed genetics, medicine, ethics, agriculture, and public imagination',
  },
  '07-06': {
    year: 2016,
    title: 'Pokemon Go Launches',
    topic: 'Pokemon Go',
    headline: 'Pokemon Go launched on smartphones, turning augmented reality into a street-level global craze.',
    text: 'Pokemon Go launched for iPhone and Android, sending players into parks, plazas, landmarks, and streets and making augmented reality feel mainstream almost overnight.',
    source: 'https://press.pokemon.com/en/GET-UP-AND-GO-POKEMON-GO-AVAILABLE-TODAY-ON-iPHONE-AND-ANDROID-DEVICES',
    sourceLabel: 'The Pokemon Company: Pokemon Go available today',
    sourceDescription: 'Official July 6, 2016 launch announcement',
    visual: 'tech',
    palette: 'neon',
    scene: 'a glowing 2016 city park at dusk with diverse players holding phones, colorful screen light, fountains, monuments, bikes, food carts, and augmented-reality excitement',
    stakes: 'a mobile-gaming moment that made location, phones, crowds, nostalgia, and augmented reality part of everyday public space',
  },
  '07-07': {
    year: 2007,
    title: 'Live Earth Concerts',
    topic: 'Live Earth',
    headline: 'Live Earth concerts connected stages across continents for climate awareness.',
    text: 'Live Earth concerts were held across the world, using pop music, television, and online media to turn climate awareness into a synchronized global entertainment event.',
    source: 'https://en.wikipedia.org/wiki/Live_Earth',
    sourceLabel: 'Wikipedia: Live Earth',
    sourceDescription: '2007 worldwide climate-benefit concerts',
    visual: 'music',
    palette: 'neon',
    scene: 'a global concert broadcast wall of saturated stage lights, crowds, cameras, green-room cables, and climate graphics without readable text',
    stakes: 'a mass-media climate moment that showed how pop spectacle could carry planetary politics',
  },
  '07-08': {
    year: 2011,
    title: 'Final Space Shuttle Launch',
    topic: 'STS-135',
    headline: 'Space Shuttle Atlantis launched on STS-135, the final mission of the Space Shuttle program.',
    text: 'Space Shuttle Atlantis launched on STS-135, closing the Space Shuttle program after three decades of reusable spacecraft, orbital construction, and public spaceflight imagery.',
    source: 'https://en.wikipedia.org/wiki/STS-135',
    sourceLabel: 'Wikipedia: STS-135',
    sourceDescription: 'Final mission of the Space Shuttle program',
    visual: 'space',
    palette: 'stage',
    scene: 'a high-saturation Florida launch morning with shuttle flame, vapor clouds, spectators, press lenses, ocean humidity, and the end of an era lifting off',
    stakes: 'a spaceflight farewell that closed a defining chapter in orbital engineering, public imagination, and reusable spacecraft',
  },
  '07-09': {
    year: 1981,
    title: 'Donkey Kong Hits Arcades',
    topic: 'Donkey Kong (1981 video game)',
    headline: 'Donkey Kong received its first arcade release in Japan, helping define platform games and Nintendo’s global future.',
    text: 'Donkey Kong received its first arcade release in Japan, helping define platform games, character-driven game design, arcade culture, and Nintendo’s path toward global dominance.',
    source: 'https://en.wikipedia.org/wiki/Donkey_Kong_(1981_video_game)',
    sourceLabel: 'Wikipedia: Donkey Kong',
    sourceDescription: '1981 arcade game and early platform-game landmark',
    visual: 'tech',
    palette: 'neon',
    scene: 'a vivid 1981 Japanese arcade with glowing cabinets, pixel light, teenagers, coins, cigarette haze, neon signs without readable text, and the birth of character-driven gaming',
    stakes: 'an arcade milestone that pushed games toward story, characters, platforming, and the global console era',
  },
  '07-10': {
    year: 1962,
    title: 'Telstar 1 Launches',
    topic: 'Telstar',
    headline: 'Telstar 1 launched, opening the age of live satellite television and modern communications satellites.',
    text: 'Telstar 1 launched from Cape Canaveral, becoming the satellite that soon relayed live transatlantic television and made communications satellites feel real to the public.',
    source: 'https://www.britannica.com/technology/Telstar-communications-satellite',
    sourceLabel: 'Britannica: Telstar',
    sourceDescription: 'Communications satellite launched in July 1962',
    visual: 'tech',
    palette: 'signal',
    scene: 'a bright 1962 communications-satellite launch and tracking station where antennas, consoles, engineers, televisions, and rocket flame connect continents',
    stakes: 'a satellite milestone that helped make live global media, phone links, and planetary communications infrastructure possible',
  },
  '07-11': {
    year: 1979,
    title: 'Skylab Falls to Earth',
    topic: 'Skylab',
    headline: 'Skylab reentered Earth’s atmosphere, scattering debris over the Indian Ocean and Western Australia.',
    text: 'Skylab reentered Earth’s atmosphere, scattering debris over the Indian Ocean and Western Australia and turning space infrastructure, media suspense, and orbital decay into a worldwide spectacle.',
    source: 'https://www.nasa.gov/history/45-years-ago-skylab-reenters-earths-atmosphere/',
    sourceLabel: 'NASA: Skylab reenters Earth’s atmosphere',
    sourceDescription: 'NASA history of Skylab reentry on July 11, 1979',
    visual: 'space',
    palette: 'neon',
    scene: 'a surreal Australian night sky streaked with burning spacecraft debris above red earth, roadside observers, radio antennas, cameras, and 1970s cars',
    stakes: 'a space-age spectacle that made orbital debris, public risk, and the physical reality of space stations visible on Earth',
  },
  '07-12': {
    year: 1998,
    title: 'France Wins the World Cup',
    topic: '1998 FIFA World Cup final',
    headline: 'France defeated Brazil to win its first FIFA World Cup title.',
    text: 'France defeated Brazil in the 1998 FIFA World Cup final, turning a diverse national team, Paris celebration, sport, identity, and mass television into a defining global football image.',
    source: 'https://en.wikipedia.org/wiki/1998_FIFA_World_Cup_final',
    sourceLabel: 'Wikipedia: 1998 FIFA World Cup final',
    sourceDescription: 'Football match in which France won its first World Cup',
    visual: 'sports',
    palette: 'stage',
    scene: 'a saturated Paris night celebration with diverse fans, stadium screens, flags, confetti, metro lights, drums, and blue-white-red reflections after a World Cup final',
    stakes: 'a sports moment where football, immigration, national identity, television, and public celebration met at global scale',
  },
  '07-13': {
    year: 1985,
    title: 'Live Aid',
    topic: 'Live Aid',
    headline: 'Live Aid concerts linked London and Philadelphia in a global music broadcast for famine relief.',
    text: 'Live Aid concerts linked London and Philadelphia in a global music broadcast, using stadium rock and television scale to raise money and attention for famine relief in Ethiopia.',
    source: 'https://en.wikipedia.org/wiki/Live_Aid',
    sourceLabel: 'Wikipedia: Live Aid',
    sourceDescription: '1985 global benefit concerts',
    visual: 'music',
    palette: 'stage',
    scene: 'a blazing 1985 stadium broadcast with colored stage lights, satellite trucks, guitar cables, crowds, control-room monitors, and global charity television energy',
    stakes: 'a pop-broadcast landmark that made live global music television feel like a planetary public square',
  },
  '07-14': {
    year: 1789,
    title: 'Storming of the Bastille',
    topic: 'Storming of the Bastille',
    headline: 'Revolutionaries stormed the Bastille in Paris, becoming an enduring symbol of the French Revolution.',
    text: 'Parisians stormed the Bastille, turning a fortress-prison into a revolutionary symbol and making July 14 a defining date in the politics of popular sovereignty.',
    source: 'https://en.wikipedia.org/wiki/Storming_of_the_Bastille',
    sourceLabel: 'Wikipedia: Storming of the Bastille',
    sourceDescription: '1789 event that became a symbol of the French Revolution',
    visual: 'protest',
    palette: 'public-square',
    scene: 'a vivid Paris street outside the Bastille with smoke, tricolor cockades, workers, women, market carts, broken gates, and revolutionary momentum without graphic violence',
    stakes: 'a revolutionary symbol that transformed monarchy, citizenship, political spectacle, and modern ideas of popular power',
  },
  '07-15': {
    year: 1983,
    title: 'Famicom Launches',
    topic: 'Family Computer',
    headline: 'Nintendo released the Family Computer in Japan, helping launch the 8-bit home-console era.',
    text: 'Nintendo released the Family Computer in Japan, helping launch the 8-bit home-console era and moving video games from arcades into family living rooms worldwide.',
    source: 'https://en.wikipedia.org/wiki/Nintendo_Entertainment_System',
    sourceLabel: 'Wikipedia: Nintendo Entertainment System',
    sourceDescription: 'Home video-game console first released as the Famicom in Japan',
    visual: 'tech',
    palette: 'neon',
    scene: 'a colorful 1983 Tokyo electronics shop with red-and-white home consoles, cartridge boxes, CRT screens, kids, parents, shelf lights, and arcade energy moving indoors',
    stakes: 'a home-console launch that reshaped play, family rooms, Japanese consumer tech, and the global video-game industry',
  },
  '07-16': {
    year: 1969,
    title: 'Apollo 11 Launches',
    topic: 'Apollo 11',
    headline: 'Apollo 11 launched from Kennedy Space Center on the first mission to land humans on the Moon.',
    text: 'Apollo 11 launched from Kennedy Space Center, beginning the mission that would land humans on the Moon and create one of the defining technological images of the twentieth century.',
    source: 'https://www.nasa.gov/mission/apollo-11/',
    sourceLabel: 'NASA: Apollo 11',
    sourceDescription: 'NASA mission page for Apollo 11',
    visual: 'space',
    palette: 'stage',
    scene: 'a vivid Saturn V launch morning with flame, vapor, grandstands, cameras, Florida heat, and the white rocket climbing into blue sky',
    stakes: 'a launch that turned spaceflight, geopolitics, engineering, television, and human ambition toward the Moon',
  },
  '07-17': {
    year: 1955,
    title: 'Disneyland Opens',
    topic: 'Disneyland',
    headline: 'Disneyland opened in Anaheim, California, broadcasting a new kind of themed entertainment to the world.',
    text: 'Disneyland opened in Anaheim, California, turning themed environments, television promotion, family tourism, fantasy architecture, and branded entertainment into a new global template.',
    source: 'https://en.wikipedia.org/wiki/Disneyland',
    sourceLabel: 'Wikipedia: Disneyland',
    sourceDescription: 'Theme park opened in 1955',
    visual: 'culture',
    palette: 'stage',
    scene: 'a candy-colored 1955 theme-park opening day with television cameras, families, midcentury clothes, flags, painted facades, heat, balloons, and chaotic wonder',
    stakes: 'a pop-culture opening that reshaped tourism, themed design, family entertainment, media synergy, and commercial imagination',
  },
  '07-18': {
    year: 1968,
    title: 'Intel Founded',
    topic: 'Intel',
    headline: 'Intel was founded in California, helping build the semiconductor foundation of modern computing.',
    text: 'Intel was founded in California, helping push memory chips, microprocessors, personal computers, data centers, and the semiconductor industry into the center of modern life.',
    source: 'https://www.intel.com/content/www/us/en/history/virtual-vault/articles/intels-founding.html',
    sourceLabel: 'Intel: Intel’s Founding',
    sourceDescription: 'Intel history page for the company founding',
    visual: 'tech',
    palette: 'signal',
    scene: 'a saturated late-1960s semiconductor lab with clean benches, wafers, microscopes, colored oscilloscope traces, notebooks, and Silicon Valley startup intensity',
    stakes: 'a chip-industry founding that fed personal computing, servers, software, mobile devices, and the digital economy',
  },
  '07-19': {
    year: 2013,
    title: 'The Day the Earth Smiled',
    topic: 'The Day the Earth Smiled',
    headline: 'Cassini photographed Saturn with Earth visible in the distance, creating The Day the Earth Smiled.',
    text: 'Cassini photographed Saturn with Earth visible in the distance, creating The Day the Earth Smiled and turning planetary science into a shared cosmic self-portrait.',
    source: 'https://en.wikipedia.org/wiki/The_Day_the_Earth_Smiled',
    sourceLabel: 'Wikipedia: The Day the Earth Smiled',
    sourceDescription: '2013 Cassini image event at Saturn',
    visual: 'space',
    palette: 'lunar',
    scene: 'a majestic Cassini-at-Saturn view with golden rings, a tiny Earth dot, spacecraft perspective, black space, and luminous planetary scale',
    stakes: 'a space-science image that made Earth’s smallness and planetary exploration emotionally public',
  },
  '07-20': {
    year: 1969,
    title: 'Apollo 11 Moon Landing',
    topic: 'Apollo 11',
    headline: 'Apollo 11’s Lunar Module Eagle landed on the Moon.',
    text: 'Apollo 11’s Lunar Module Eagle landed on the Moon, making the first human landing on another world and becoming one of the central technological memories of the twentieth century.',
    source: 'https://www.nasa.gov/mission/apollo-11/',
    sourceLabel: 'NASA: Apollo 11',
    sourceDescription: 'NASA mission page for Apollo 11',
    visual: 'space',
    palette: 'lunar',
    scene: 'a high-contrast lunar surface with Eagle’s landing legs, dust, gold foil, long shadows, black sky, and Earth hanging above the Sea of Tranquility',
    stakes: 'a Moon landing that fused engineering, geopolitics, television, risk, and human imagination into one image',
  },
  '07-21': {
    year: 2007,
    title: 'Final Harry Potter Book Released',
    topic: 'Harry Potter and the Deathly Hallows',
    headline: 'Harry Potter and the Deathly Hallows was released worldwide, ending the core book series.',
    text: 'Harry Potter and the Deathly Hallows was released worldwide, turning midnight book lines, secrecy, spoilers, fandom, and global publishing into a shared cultural finale.',
    source: 'https://en.wikipedia.org/wiki/Harry_Potter_and_the_Deathly_Hallows',
    sourceLabel: 'Wikipedia: Harry Potter and the Deathly Hallows',
    sourceDescription: 'Final novel in the Harry Potter series, released in 2007',
    visual: 'culture',
    palette: 'neon',
    scene: 'a saturated midnight bookstore release with diverse readers, costumes, streetlights, stacks of sealed books, cameras, coffee cups, and all-ages anticipation',
    stakes: 'a global fandom finale that showed how books could still create mass public ritual in the internet age',
  },
  '07-22': {
    year: 1933,
    title: 'First Solo Around-the-World Flight Completed',
    topic: 'Wiley Post',
    headline: 'Wiley Post completed the first solo flight around the world.',
    text: 'Wiley Post completed the first solo flight around the world, proving long-distance aviation, navigation, endurance, and global news spectacle could fit inside one aircraft journey.',
    source: 'https://en.wikipedia.org/wiki/Wiley_Post',
    sourceLabel: 'Wikipedia: Wiley Post',
    sourceDescription: 'American aviator who completed the first solo flight around the world',
    visual: 'transport',
    palette: 'voyage',
    scene: 'a colorful 1933 airfield arrival with a scarred aircraft, flashbulb cameras, oil-stained mechanics, maps, crowd ropes, and around-the-world aviation glamour',
    stakes: 'an aviation milestone that made the planet feel smaller through speed, radio, navigation, celebrity, and machines',
  },
  '07-23': {
    year: 1962,
    title: 'First Live Transatlantic TV Broadcast',
    topic: 'Telstar',
    headline: 'Telstar relayed the first publicly available live transatlantic television broadcast.',
    text: 'Telstar relayed the first publicly available live transatlantic television broadcast, linking North America and Europe by satellite and changing the scale of live media.',
    source: 'https://www.wired.com/2012/07/july-23-1962-telstar-provides-first-ever-tv-link-between-u-s-europe/',
    sourceLabel: 'WIRED: Telstar provides first TV link',
    sourceDescription: 'Account of Telstar’s July 23, 1962 transatlantic television broadcast',
    visual: 'tech',
    palette: 'signal',
    scene: 'a radiant 1962 broadcast-control room with wall clocks, CRT monitors showing blurred landmarks, satellite dishes, engineers, cables, and blue-white signal glow',
    stakes: 'a live-media breakthrough that made television planetary and helped build the expectation of instant global connection',
  },
  '07-24': {
    year: 1969,
    title: 'Apollo 11 Returns to Earth',
    topic: 'Apollo 11',
    headline: 'Apollo 11 splashed down safely in the Pacific Ocean, completing the first Moon landing mission.',
    text: 'Apollo 11 splashed down safely in the Pacific Ocean, completing the first Moon landing mission as recovery crews, quarantine procedures, and global television turned triumph into return.',
    source: 'https://www.nasa.gov/mission/apollo-11/',
    sourceLabel: 'NASA: Apollo 11',
    sourceDescription: 'NASA mission page for Apollo 11',
    visual: 'space',
    palette: 'voyage',
    scene: 'a bright Pacific recovery scene with orange capsule, Navy divers, helicopter spray, carrier deck, flotation collars, cameras, and the astronauts’ return from the Moon',
    stakes: 'a spaceflight return that completed the Moon landing story and brought its risk, engineering, and spectacle back to Earth',
  },
};

function collapseWhitespace(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function formatYear(year) {
  const value = Number(year);
  if (!Number.isFinite(value)) return '';
  return value < 0 ? `${Math.abs(value)} BCE` : String(value);
}

function makeFacts(dateKey, moment) {
  return [
    { label: 'Date', value: moment.displayDate || dateKey },
    { label: 'Year', value: formatYear(moment.year) },
    { label: 'Scale', value: 'world-historical' },
    { label: 'Main scene', value: moment.scene },
    { label: 'Impact', value: moment.stakes },
  ];
}

function makeSummary(dateKey, moment) {
  const date = moment.displayDate || dateKey;
  const year = formatYear(moment.year);
  return [
    `Set the dial to ${date}, ${year}. ${moment.text} This entry is selected because it is not just an interesting anniversary; it is one of the larger world-historical turns available on this date.`,
    `The image should treat the day as a living scene, not a trivia caption. Picture ${moment.scene}. The frame should make the viewer feel the materials of the moment: weather, light, machinery, clothing, documents, stone, water, smoke, crowds, silence, or whatever physical details made history happen in public.`,
    `The stakes are clear: ${moment.stakes}. That is why this moment belongs in the daily feature. It changed how people moved, fought, communicated, governed, imagined, remembered, survived, or understood power.`,
    `The visual standard is museum-grade photorealism. No generic podiums, no handshakes, no people standing around tables unless the event absolutely demands it. The image needs a specific place, a specific atmosphere, a specific camera angle, and enough historical detail to feel witnessed rather than invented.`,
    `Diversity matters here in both subject and viewpoint. The sequence should move across regions, communities, classes, genders, technologies, landscapes, and emotional registers, always centering the people and places most connected to the event instead of defaulting to the most familiar official face.`,
  ].map(collapseWhitespace);
}

function makeArtPrompt(dateKey, moment) {
  return [
    'Use case: historical-scene',
    'Asset type: daily website feature image for "On This Day in History"',
    `Date/event: ${moment.displayDate || dateKey}, ${formatYear(moment.year)}: ${moment.title}.`,
    `Core historical fact: ${moment.text}`,
    `Scene/backdrop: ${moment.scene}.`,
    `Impact: ${moment.stakes}.`,
    'Visual standard: historically accurate, visually unforgettable, museum-grade photorealistic image. Make the viewer feel like they are witnessing history itself, not a generic AI recreation.',
    'Avoid: repetitive table scenes, generic politicians shaking hands, static portrait shots, crowds staring at camera, symbolic poster art, readable text, labels, logos, watermark, UI, modern anachronisms.',
  ].join('\n');
}

function wordCount(summary) {
  return summary.join(' ').split(/\s+/).filter(Boolean).length;
}

const context = { window: {} };
vm.runInNewContext(fs.readFileSync(momentsFile, 'utf8'), context);
const moments = context.window.PRESS_ON_THIS_DAY_MOMENTS || {};
const attribution = context.window.PRESS_ON_THIS_DAY_ATTRIBUTION || {};

for (const [dateKey, override] of Object.entries(CURATED)) {
  const previous = moments[dateKey] || { date: dateKey, displayDate: dateKey };
  const moment = {
    ...previous,
    ...override,
    date: dateKey,
    displayDate: previous.displayDate || dateKey,
    related: [],
  };
  moment.dek = `Step into ${formatYear(moment.year)}: ${moment.headline}`;
  moment.facts = makeFacts(dateKey, moment);
  moment.summary = makeSummary(dateKey, moment);
  moment.coolFacts = [
    `${moment.displayDate} drops into ${formatYear(moment.year)}, with a genuinely world-historical event rather than a minor archive item.`,
    moment.text,
    `Why it matters: ${moment.stakes}.`,
    `What to picture: ${moment.scene}.`,
  ];
  moment.artPrompt = makeArtPrompt(dateKey, moment);
  moment.wordCount = wordCount(moment.summary);
  moments[dateKey] = moment;
}

const updatedAttribution = {
  ...attribution,
  curationPolicy: 'First-month live run prioritizes major world-historical events for the exact calendar date, not minor or merely interesting anniversaries.',
  generatedAt: new Date().toISOString(),
};

fs.writeFileSync(
  momentsFile,
  `/*\n  Daily On This Day history moments for The Press.\n  Generated from Wikipedia's selected On This Day API and curated for world-historical significance.\n*/\nwindow.PRESS_ON_THIS_DAY_ATTRIBUTION = ${JSON.stringify(updatedAttribution, null, 2)};\nwindow.PRESS_ON_THIS_DAY_MOMENTS = ${JSON.stringify(moments, null, 2)};\n`,
);

console.log(JSON.stringify({ updated: Object.keys(CURATED).length, dates: Object.keys(CURATED) }, null, 2));
